export const dataTableStyles = {
  wrapper: 'relative w-full overflow-auto',
  root: 'w-full caption-bottom text-sm',
  header: '[&_tr]:border-b [&_tr]:border-base-200',
  body: '[&_tr:last-child]:border-0',
  row: 'border-b border-base-200 transition-colors',
  rowHoverable: 'hover:bg-base-200/30',
  rowStriped: 'even:bg-base-50',
  head: 'h-10 px-3 text-left align-middle font-medium text-base-content/70',
  headSortable: 'cursor-pointer select-none hover:text-base-content transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary',
  headCompact: 'h-8 px-2 text-xs',
  cell: 'p-3 align-middle',
  cellCompact: 'p-2 text-xs',
  cellBordered: 'border-x border-base-200 first:border-l-0 last:border-r-0',
  caption: 'mt-4 text-sm text-base-content/70',
  empty: 'h-24 text-center text-base-content/70',
  sortIcon: 'inline-block ml-1 size-3.5 align-middle text-base-content/70',
  sortIconActive: 'text-base-content',
  loading: 'absolute inset-0 flex items-center justify-center bg-base-100/60',
};
